### PR TITLE
convert to go modules

### PR DESCRIPTION
**Pull request by thomasf**
No dependency versions upgraded.

Minimum go version increased to 1.13 for convenience because it's the first version that auto detects go modules to not having to add more build information to readme.

### CODE REVIEW

**Comment by inverse** [comment]
@AD7six any chance this can get merged?

**Comment by teintuc** [comment]
Yes a merge of this PR would be much appreciated :)

**Comment by AD7six** [comment]
> @AD7six any chance this can get merged?

I am not involved in the maintenance of this repository, but I've raised it to the internal team that is in case it was missed. These are busy times, but it'll be reviewed in due course :).

**Comment by inverse** [comment]
@josegonzalez another worthwhile one to merge

**Comment by inverse** [comment]
Thanks!

**Pull request merged**
