### PR TITLE
Add support for ECR public registries

### PR DESCRIPTION
**Pull request by Saber-W**
This PR adds support for ECR public registries besides current ECR private registries support. Users could mirror the repositories to their ECR public registries by setting the `target.registry` value to something like `public.ecr.aws/REGISTRY_ALIAS`.

This PR is the first one of a series to resolve issue #77. Thanks!

cc @alolita

### CODE REVIEW

**Review by alolita — COMMENTED** [review]
A couple of comments - 
in main.go cfg.Region = "us-east-1" should not be hardcoded
in readme comments in lines 81 and 82 referring to private and then public example is confusing

**Review by alolita — DISMISSED** [review]

**Comment by Saber-W** [comment]
Hi @josegonzalez, please review this PR and the second one (#79) when you have time. Thanks!

**Comment by josegonzalez** [comment]
Mind running `go fmt` against the project?

**Comment by ArchiFleKs** [comment]
Does this PR also handle public repository creation ? I'm getting an `The repository with name 'alpine' does not exist in the registry with id` when trying to push to a public ECR and the repository does not exist

**Comment by Saber-W** [comment]
Hi @ArchiFleKs, yes, it will create one if not exist. Have you loged in your ECR public registry before this tool runs? `aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/YOUR_ECR_PUBLIC_SUFFIX`

**Comment by ArchiFleKs** [comment]
@Saber-W yes I did, it work only when I create the public ECR repo before running this. I'm using Github action here is my workflow:

```
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PRODUCTION }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Public ECR
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID_PRODUCTION }}
        password: ${{ secrets.AWS_SECRET_ACCESS_PRODUCTION }}
      env:
        AWS_REGION: us-east-1

    - name: Instal Docker Mirror
      run: |
        curl -L https://github.com/seatgeek/docker-mirror/releases/download/${{ env.DOCKER_MIRROR_VERSION }}/docker-mirror-linux-amd64 -o /usr/local/bin/docker-mirror && chmod +x /usr/local/bin/docker-mirror
    - name: Run Docker Mirror
      run: |
        docker-mirror
```

Pushing is working and AWS user has full access to ECR and can create repo. But is does not seem to try to create it.

Here is my config:

```
---
cleanup: true # (optional) Clean the mirrored images (default: false)
target:
  # where to copy images to
  # Below is an example of the ECR private registry.
  # To mirror repositories to a ECR public registry, replace this value with public.ecr.aws/YOUR_ECR_PUBLIC_ALIAS
  registry: public.ecr.aws
  prefix: "REDACTED_AWS_GENERATED_ID/"
# what repositories to copy
repositories:
    # will automatically know it's a "library" repository in dockerhub
  - name: alpine
    match_tag: # tags to match, can be specific or glob pattern
      - "3.*" # specific tag match
      - "3"
    max_tag_age: 8w # only import tags that are 8w or less old

  - name: vault
    match_tag: # tags to match, can be specific or glob pattern
      - "1.*" # specific tag match
    max_tag_age: 24w # only import tags that are 8w or less old

  - name: hashicorp/vault-k8s
    match_tag: # tags to match, can be specific or glob pattern
      - "0.*" # specific tag match
    max_tag_age: 24w # only import tags that are 8w or less old
```

**Pull request merged**
