### PR TITLE
Handle pagination when listing image tags

### PR DESCRIPTION
**Pull request by ctbur**
This PR fixes a bug where some tags would not be synchronized when a repository had too many tags to fit into one request.

Co-authored by @inverse

### CODE REVIEW

**Comment by josegonzalez** [comment]
Do you have an example repository we can use to test this?

**Comment by inverse** [comment]
@josegonzalez What about this: https://hub.docker.com/r/armory/halyard-armory/

**Comment by n1ru4l** [comment]
try

```
  - name: redis
    match_tag:
      - "5.0.3-alpine"
```

**Review by n1ru4l — APPROVED** [review]
I can confirm that this solves the issue where a tag is not getting synced (aka cannot be found) to ECR

**Comment by inverse** [comment]
@josegonzalez any chance this can get merged? It really is an improvement for this project

**Comment by josegonzalez** [comment]
This needs a rebase now that we added auth. Does anyone want to take that up?

**Comment by inverse** [comment]
@josegonzalez updated 👍🏼

**Comment by josegonzalez** [comment]
@inverse im assuming you've tested the update as well? :)

**Comment by inverse** [comment]
@josegonzalez just tested now 👍🏼

**Pull request merged**
